name = "health-ready-api"
main = "src/index.ts"
compatibility_date = "2026-06-13"
compatibility_flags = ["nodejs_compat"]

[vars]
ALLOWED_ORIGIN = "http://localhost:5173"

[[d1_databases]]
binding = "DB"
database_name = "health-ready"
database_id = "e7e03fa6-f8b4-4343-8716-c2053e31e8e0"
migrations_dir = "migrations"
